<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class AffiliateNetworkSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $networks = [
            [
                'name' => 'Fiverr',
                'slug' => 'fiverr',
                'description' => 'The world\'s largest marketplace for freelance services',
                'detailed_description' => 'Fiverr is a global online marketplace for freelance services. As an affiliate, you can earn commissions by referring new freelancers or buyers to the platform. Fiverr offers competitive commission rates and provides extensive marketing materials to help affiliates succeed. The platform is trusted by millions of users worldwide and offers opportunities in various service categories including design, writing, programming, marketing, and more.',
                'base_url' => 'https://www.fiverr.com',
                'registration_url' => 'https://affiliates.fiverr.com/join',
                'logo_url' => null,
                'category' => 'freelancing',
                'commission_rate' => '10% recurring + $150 per seller',
                'payment_methods' => ['PayPal', 'Bank Transfer', 'Fiverr Credits'],
                'minimum_payout' => '$20',
                'payout_frequency' => 'Monthly',
                'features' => [
                    'Recurring commissions on subscriptions',
                    '$150 bonus per referred seller',
                    'Cookie duration: 90 days',
                    'Comprehensive tracking dashboard',
                    'Dedicated affiliate manager',
                    'Marketing materials provided',
                    'Real-time reporting',
                ],
                'pros' => [
                    'High brand recognition',
                    'Recurring commissions',
                    'Good cookie duration',
                    'Bonus payments available',
                    'Wide range of services to promote',
                ],
                'cons' => [
                    'Competitive market',
                    'Requires marketing strategy',
                    'Commission varies by referral type',
                ],
                'learn_more_credit_cost' => 3,
                'country_availability' => null,
                'is_active' => true,
            ],
            [
                'name' => 'Udemy',
                'slug' => 'udemy',
                'description' => 'Online learning platform with thousands of courses',
                'detailed_description' => 'Udemy is one of the largest online learning platforms, offering over 200,000 courses across various subjects. As an Udemy affiliate, you can promote courses and earn commissions on every sale. The platform offers excellent course quality, lifetime access for students, and mobile app support. Affiliates benefit from a 97% commission rate for the first month when students are new to Udemy.',
                'base_url' => 'https://www.udemy.com',
                'registration_url' => 'https://www.udemy.com/affiliate/',
                'logo_url' => null,
                'category' => 'education',
                'commission_rate' => '97% for new students (first purchase), then 3%',
                'payment_methods' => ['PayPal', 'Bank Transfer'],
                'minimum_payout' => '$10',
                'payout_frequency' => 'Monthly',
                'features' => [
                    'High commission rate for new students',
                    'Cookie duration: 7 days',
                    'Access to promotional materials',
                    'Real-time tracking',
                    'Mobile app support',
                    'Wide variety of courses',
                    'Lifetime access for students',
                ],
                'pros' => [
                    'Very high commission for new customers',
                    'Large course library',
                    'Growing market',
                    'Easy to promote',
                ],
                'cons' => [
                    'Lower commission for returning customers',
                    'Short cookie duration',
                ],
                'learn_more_credit_cost' => 3,
                'country_availability' => null,
                'is_active' => true,
            ],
            [
                'name' => 'Digistore24',
                'slug' => 'digistore24',
                'description' => 'Digital product marketplace and affiliate network',
                'detailed_description' => 'Digistore24 is a comprehensive digital product marketplace and affiliate network, primarily focused on the German market but expanding globally. It offers digital products across various niches including software, e-books, online courses, and memberships. The platform provides excellent affiliate tools, detailed statistics, and supports multiple payment methods.',
                'base_url' => 'https://www.digistore24.com',
                'registration_url' => 'https://www.digistore24.com/page/affiliate',
                'logo_url' => null,
                'category' => 'ecommerce',
                'commission_rate' => '10% - 70% (varies by product)',
                'payment_methods' => ['PayPal', 'Bank Transfer', 'SEPA', 'Credit Card'],
                'minimum_payout' => '€10',
                'payout_frequency' => 'Monthly',
                'features' => [
                    'Wide range of digital products',
                    'Flexible commission rates',
                    'Cookie duration: 30-90 days',
                    'Detailed analytics',
                    'Marketing tools provided',
                    'Multi-language support',
                    'Recurring commissions on subscriptions',
                ],
                'pros' => [
                    'High commission potential',
                    'Good cookie duration',
                    'Recurring commissions available',
                    'Strong German market presence',
                ],
                'cons' => [
                    'Primarily German market',
                    'Commission varies significantly',
                ],
                'learn_more_credit_cost' => 3,
                'country_availability' => null,
                'is_active' => true,
            ],
            [
                'name' => 'CPA Grip',
                'slug' => 'cpa-grip',
                'description' => 'CPA affiliate network for performance marketing',
                'detailed_description' => 'CPA Grip is a popular CPA (Cost Per Action) affiliate network offering thousands of offers across various verticals including finance, health, gaming, and mobile. The network provides excellent support, fast payments, and detailed tracking. CPA Grip is particularly popular for its simplicity and beginner-friendly approach to CPA marketing.',
                'base_url' => 'https://www.cpagrip.com',
                'registration_url' => 'https://www.cpagrip.com/join.php',
                'logo_url' => null,
                'category' => 'cpa',
                'commission_rate' => '$0.10 - $50+ per conversion (varies by offer)',
                'payment_methods' => ['PayPal', 'Payoneer', 'Bank Wire', 'Cryptocurrency'],
                'minimum_payout' => '$5',
                'payout_frequency' => 'Weekly',
                'features' => [
                    'Thousands of CPA offers',
                    'Fast weekly payments',
                    'Low minimum payout',
                    'Multiple payment methods',
                    'Real-time tracking',
                    'Detailed analytics',
                    '24/7 support',
                    'Offer recommendation tool',
                ],
                'pros' => [
                    'Very low minimum payout',
                    'Fast payments',
                    'Beginner-friendly',
                    'Wide variety of offers',
                    'Flexible payment options',
                ],
                'cons' => [
                    'Competitive market',
                    'Commission rates vary widely',
                ],
                'learn_more_credit_cost' => 2,
                'country_availability' => null,
                'is_active' => true,
            ],
            [
                'name' => 'Deriv',
                'slug' => 'deriv',
                'description' => 'Online trading platform for forex and derivatives',
                'detailed_description' => 'Deriv is a leading online trading platform offering forex, CFDs, and synthetic indices trading. The platform is regulated and provides a wide range of trading instruments. As a Deriv affiliate, you earn commissions on trader referrals with competitive rates and lifetime commissions on certain tiers. The platform offers excellent trading tools and supports multiple languages.',
                'base_url' => 'https://deriv.com',
                'registration_url' => 'https://deriv.com/partners/',
                'logo_url' => null,
                'category' => 'forex',
                'commission_rate' => 'Up to $500 per active trader + recurring commissions',
                'payment_methods' => ['Bank Transfer', 'Cryptocurrency', 'Skrill', 'Neteller'],
                'minimum_payout' => '$100',
                'payout_frequency' => 'Monthly',
                'features' => [
                    'Lifetime commissions on higher tiers',
                    'Performance bonuses',
                    'Multi-asset trading platform',
                    'Advanced trading tools',
                    'Regulated broker',
                    '24/7 support',
                    'Multiple languages',
                    'Dedicated affiliate manager',
                ],
                'pros' => [
                    'High commission potential',
                    'Lifetime commissions available',
                    'Regulated platform',
                    'Performance bonuses',
                ],
                'cons' => [
                    'Higher minimum payout',
                    'Regulatory restrictions in some countries',
                ],
                'learn_more_credit_cost' => 4,
                'country_availability' => null,
                'is_active' => true,
            ],
            [
                'name' => 'Exness',
                'slug' => 'exness',
                'description' => 'Global forex and CFD broker with competitive spreads',
                'detailed_description' => 'Exness is a well-established global forex and CFD broker known for low spreads, fast execution, and excellent customer support. The affiliate program offers competitive commission structures with both revenue share and CPA models. Exness is regulated in multiple jurisdictions and provides comprehensive trading tools and platforms.',
                'base_url' => 'https://www.exness.com',
                'registration_url' => 'https://partners.exness.com/',
                'logo_url' => null,
                'category' => 'forex',
                'commission_rate' => 'Up to 50% revenue share or CPA model',
                'payment_methods' => ['Bank Transfer', 'Skrill', 'Neteller', 'Cryptocurrency'],
                'minimum_payout' => '$50',
                'payout_frequency' => 'Monthly',
                'features' => [
                    'Revenue share or CPA options',
                    'Competitive spreads',
                    'Fast execution',
                    'Multiple account types',
                    'Regulated broker',
                    '24/7 customer support',
                    'Advanced trading platforms',
                    'Performance bonuses',
                ],
                'pros' => [
                    'Flexible commission models',
                    'Strong brand reputation',
                    'Good trading conditions',
                    'Regulated',
                ],
                'cons' => [
                    'Competitive market',
                    'Regulatory restrictions apply',
                ],
                'learn_more_credit_cost' => 4,
                'country_availability' => null,
                'is_active' => true,
            ],
            [
                'name' => 'HF Markets',
                'slug' => 'hf-markets',
                'description' => 'Award-winning forex and CFD broker',
                'detailed_description' => 'HF Markets (formerly HotForex) is an award-winning forex and CFD broker offering trading services to clients worldwide. The affiliate program provides generous commissions and support. The broker is regulated by multiple authorities and offers competitive trading conditions with excellent execution speeds.',
                'base_url' => 'https://www.hfmarkets.com',
                'registration_url' => 'https://www.hfmarkets.com/int/partners/affiliates',
                'logo_url' => null,
                'category' => 'forex',
                'commission_rate' => 'Up to $4 per lot + performance bonuses',
                'payment_methods' => ['Bank Transfer', 'Skrill', 'Neteller', 'Credit Card'],
                'minimum_payout' => '$50',
                'payout_frequency' => 'Monthly',
                'features' => [
                    'Multiple commission models',
                    'Performance bonuses',
                    'Regulated broker',
                    'Award-winning platform',
                    'Competitive spreads',
                    '24/7 support',
                    'Educational resources',
                    'Marketing materials',
                ],
                'pros' => [
                    'Strong reputation',
                    'Multiple commission options',
                    'Performance incentives',
                    'Well-regulated',
                ],
                'cons' => [
                    'Competitive market',
                    'Higher minimum payout',
                ],
                'learn_more_credit_cost' => 4,
                'country_availability' => null,
                'is_active' => true,
            ],
            [
                'name' => 'IC Markets',
                'slug' => 'ic-markets',
                'description' => 'Raw spread forex and CFD broker',
                'detailed_description' => 'IC Markets is a leading forex and CFD broker specializing in raw spreads and ECN trading. The platform is popular among professional traders for its tight spreads, fast execution, and advanced trading tools. The affiliate program offers competitive commissions with lifetime revenue share opportunities.',
                'base_url' => 'https://www.icmarkets.com',
                'registration_url' => 'https://www.icmarkets.com/partners/',
                'logo_url' => null,
                'category' => 'forex',
                'commission_rate' => 'Up to $7 per lot or revenue share',
                'payment_methods' => ['Bank Transfer', 'Skrill', 'Neteller', 'Credit Card'],
                'minimum_payout' => '$50',
                'payout_frequency' => 'Monthly',
                'features' => [
                    'Raw spreads',
                    'ECN trading',
                    'Advanced platforms',
                    'Fast execution',
                    'Regulated broker',
                    'Lifetime commissions',
                    'Performance bonuses',
                    'Dedicated support',
                ],
                'pros' => [
                    'Excellent trading conditions',
                    'Popular with professionals',
                    'Lifetime commissions',
                    'Strong reputation',
                ],
                'cons' => [
                    'More suitable for experienced traders',
                    'Regulatory restrictions',
                ],
                'learn_more_credit_cost' => 4,
                'country_availability' => null,
                'is_active' => true,
            ],
            [
                'name' => 'Pocket Option',
                'slug' => 'pocket-option',
                'description' => 'Binary options and forex trading platform',
                'detailed_description' => 'Pocket Option is a binary options and forex trading platform offering various trading instruments. The platform provides an intuitive interface, demo accounts, and competitive payouts. The affiliate program offers generous commissions and various promotional tools to help affiliates succeed.',
                'base_url' => 'https://pocketoption.com',
                'registration_url' => 'https://pocketoption.com/en/affiliate',
                'logo_url' => null,
                'category' => 'forex',
                'commission_rate' => 'Up to 50% revenue share',
                'payment_methods' => ['Cryptocurrency', 'Bank Transfer', 'E-wallets'],
                'minimum_payout' => '$50',
                'payout_frequency' => 'Monthly',
                'features' => [
                    'Binary options trading',
                    'Forex trading',
                    'Demo accounts',
                    'Mobile app',
                    'Social trading features',
                    'Competitive payouts',
                    'Marketing tools',
                    'Real-time tracking',
                ],
                'pros' => [
                    'User-friendly platform',
                    'High revenue share',
                    'Multiple trading options',
                    'Demo accounts available',
                ],
                'cons' => [
                    'Binary options restricted in some regions',
                    'Regulatory concerns in some jurisdictions',
                ],
                'learn_more_credit_cost' => 4,
                'country_availability' => null,
                'is_active' => true,
            ],
            [
                'name' => 'Jumia',
                'slug' => 'jumia',
                'description' => 'E-commerce platform in Kenya and Africa',
                'detailed_description' => 'Jumia is the leading e-commerce platform in Africa, operating in multiple countries across the continent. As an affiliate, you can earn commissions by promoting products from various categories. The platform offers localized content, mobile apps, and payment solutions tailored to African markets. Jumia provides excellent opportunities for affiliates targeting African markets.',
                'base_url' => 'https://www.jumia.co.ke',
                'registration_url' => 'https://affiliate.jumia.com/',
                'logo_url' => null,
                'category' => 'ecommerce',
                'commission_rate' => '1% - 5% (varies by category)',
                'payment_methods' => ['Bank Transfer', 'Mobile Money', 'PayPal'],
                'minimum_payout' => '$25',
                'payout_frequency' => 'Monthly',
                'features' => [
                    'Pan-African reach',
                    'Multiple product categories',
                    'Localized content',
                    'Mobile app support',
                    'Cash on delivery',
                    'Marketing materials',
                    'Real-time tracking',
                    'Local payment methods',
                ],
                'pros' => [
                    'Strong African market presence',
                    'Growing market',
                    'Multiple categories',
                    'Localized approach',
                ],
                'cons' => [
                    'Lower commission rates',
                    'Limited to African markets',
                ],
                'learn_more_credit_cost' => 3,
                'country_availability' => ['KE', 'NG', 'EG', 'ZA', 'GH'],
                'is_active' => true,
            ],
            [
                'name' => 'Amazon Associates',
                'slug' => 'amazon-associates',
                'description' => 'World\'s largest affiliate program',
                'detailed_description' => 'Amazon Associates is the largest affiliate marketing program globally, allowing affiliates to earn commissions on millions of products. The program offers competitive rates, extensive product selection, and excellent tracking tools. With Amazon\'s trusted brand, affiliates can promote products across virtually any niche. The program provides site strips, native shopping ads, and various promotional tools.',
                'base_url' => 'https://www.amazon.com',
                'registration_url' => 'https://affiliate-program.amazon.com/',
                'logo_url' => null,
                'category' => 'ecommerce',
                'commission_rate' => '1% - 10% (varies by category)',
                'payment_methods' => ['Bank Transfer', 'Amazon Gift Card', 'Check'],
                'minimum_payout' => '$10',
                'payout_frequency' => 'Monthly',
                'features' => [
                    'Millions of products',
                    'Multiple commission rates',
                    'Cookie duration: 24 hours',
                    'Site Stripe tool',
                    'Native shopping ads',
                    'Link localization',
                    'Real-time reporting',
                    'Promotional tools',
                ],
                'pros' => [
                    'Largest product selection',
                    'Trusted brand',
                    'Global reach',
                    'Easy to implement',
                ],
                'cons' => [
                    'Short cookie duration',
                    'Lower commission rates',
                    'Strict policies',
                ],
                'learn_more_credit_cost' => 3,
                'country_availability' => null,
                'is_active' => true,
            ],
            [
                'name' => 'Shopify',
                'slug' => 'shopify',
                'description' => 'E-commerce platform affiliate program',
                'detailed_description' => 'Shopify\'s affiliate program allows you to earn commissions by referring merchants to the Shopify platform. The program offers generous commissions with recurring payments for successful referrals. Shopify is one of the leading e-commerce platforms, making it easy to promote to entrepreneurs and businesses looking to start online stores.',
                'base_url' => 'https://www.shopify.com',
                'registration_url' => 'https://www.shopify.com/partners',
                'logo_url' => null,
                'category' => 'ecommerce',
                'commission_rate' => '$200 per sale or 200% of monthly subscription',
                'payment_methods' => ['PayPal', 'Bank Transfer'],
                'minimum_payout' => '$50',
                'payout_frequency' => 'Monthly',
                'features' => [
                    'High one-time commission',
                    'Recurring commissions',
                    'Cookie duration: 30 days',
                    'Marketing resources',
                    'Dedicated partner support',
                    'Partner dashboard',
                    'Co-marketing opportunities',
                    'Educational resources',
                ],
                'pros' => [
                    'Very high commissions',
                    'Recurring payments',
                    'Strong brand',
                    'Growing market',
                ],
                'cons' => [
                    'Requires business-focused audience',
                    'Longer sales cycle',
                ],
                'learn_more_credit_cost' => 4,
                'country_availability' => null,
                'is_active' => true,
            ],
            [
                'name' => 'OGAds',
                'slug' => 'ogads',
                'description' => 'Content locker CPA network',
                'detailed_description' => 'OGAds is a popular content locker CPA network specializing in incentivized traffic. The platform offers various offers including mobile app installs, email submits, and other incentivized actions. OGAds provides excellent tools for content locking, link shortening, and conversion optimization. The network is particularly popular among content creators and mobile marketers.',
                'base_url' => 'https://ogads.com',
                'registration_url' => 'https://ogads.com/signup',
                'logo_url' => null,
                'category' => 'cpa',
                'commission_rate' => '$0.05 - $5+ per conversion (varies by offer)',
                'payment_methods' => ['PayPal', 'Payoneer', 'Bank Wire'],
                'minimum_payout' => '$5',
                'payout_frequency' => 'Weekly',
                'features' => [
                    'Content locker tool',
                    'Link shortener',
                    'Mobile app installs',
                    'Email submits',
                    'Real-time tracking',
                    'Multiple offer types',
                    'Low minimum payout',
                    'Fast payments',
                ],
                'pros' => [
                    'Very low minimum payout',
                    'Fast weekly payments',
                    'Content locker tools',
                    'Good for mobile traffic',
                ],
                'cons' => [
                    'Lower commission rates',
                    'Limited to incentivized traffic',
                ],
                'learn_more_credit_cost' => 2,
                'country_availability' => null,
                'is_active' => true,
            ],
            [
                'name' => 'MaxBounty',
                'slug' => 'maxbounty',
                'description' => 'Premium CPA affiliate network',
                'detailed_description' => 'MaxBounty is a premium CPA affiliate network known for high-quality offers and excellent support. The network offers thousands of CPA offers across various verticals with competitive payouts. MaxBounty provides dedicated account managers, detailed analytics, and various promotional tools. The network is selective but offers excellent opportunities for serious affiliates.',
                'base_url' => 'https://www.maxbounty.com',
                'registration_url' => 'https://www.maxbounty.com/apply',
                'logo_url' => null,
                'category' => 'cpa',
                'commission_rate' => '$1 - $100+ per conversion (varies by offer)',
                'payment_methods' => ['PayPal', 'Payoneer', 'Bank Wire', 'Check'],
                'minimum_payout' => '$100',
                'payout_frequency' => 'Weekly',
                'features' => [
                    'High-quality offers',
                    'Dedicated account managers',
                    'Competitive payouts',
                    'Fast weekly payments',
                    'Detailed reporting',
                    'Multiple verticals',
                    '24/7 support',
                    'Marketing materials',
                ],
                'pros' => [
                    'Premium network',
                    'High payouts',
                    'Excellent support',
                    'Quality offers',
                ],
                'cons' => [
                    'Selective approval process',
                    'Higher minimum payout',
                ],
                'learn_more_credit_cost' => 3,
                'country_availability' => null,
                'is_active' => true,
            ],
        ];

        foreach ($networks as $networkData) {
            \App\Models\AffiliateNetwork::updateOrCreate(
                ['slug' => $networkData['slug']],
                $networkData
            );
        }
    }
}
